env: "gymma"

env_args:
  key: "Foraging-8x8-4p-2f-v2"
  time_limit: 100
  pretrained_wrapper: null

test_greedy: True
test_nepisode: 100
test_interval: 10000
log_interval: 25000
runner_log_interval: 5000
learner_log_interval: 5000
runner_log_heatmaps_interval: 50000 # Log heatmaps every {} timesteps
t_max: 5000000
render: False
allow_custom_rewards: True