env: sc2custom

env_args:
  continuing_episode: False
  difficulty: "7"
  game_version: null
  map_name: "corridor"
  move_amount: 2
  obs_all_health: True
  obs_instead_of_state: False
  obs_last_action: False
  obs_own_health: True
  obs_pathing_grid: False
  obs_terrain_height: False
  obs_timestep_number: False
  reward_death_value: 10
  reward_defeat: 0
  reward_negative_scale: 0.5
  reward_only_positive: True
  reward_scale: True
  reward_scale_rate: 20
  reward_sparse: False
  reward_win: 200
  replay_dir: ""
  replay_prefix: ""
  state_last_action: False
  state_timestep_number: False
  step_mul: 8
  seed: null
  heuristic_ai: False
  heuristic_rest: False
  debug: False

  behaviour_stayTogether_min_delta: 1.75  # minimum reduced distance between a group of allys to trigger reward
  behaviour_teamUp_min_delta: 0.9    # minimum reduced distance to a specific ally to trigger reward