behaviours:
  stayTogether:
    reward: 10
    enabled: true
  teamUp:
    reward: 10
    enabled: true
  notAttacking:
    reward: -10
    enabled: true
  attackingSame:
    reward: 10
    enabled: true

