behaviours:
  stayTogether:
    reward: 10
    enabled: false
  teamUp:
    reward: 10
    enabled: false
  notAttacking:
    reward: -10
    enabled: false
  attackingSame:
    reward: 10
    enabled: false
