allow_custom_rewards: True
punish_only_agent_not_attacking: True
reward_movement: True
reward_attacking_same_enemy: True

punish_only_agent_not_attacking_multiplier: 0.5
reward_movement_multiplier: 0.01
reward_attacking_same_enemy_multiplier: 10
